@startuml 1
skinparam dpi 150
' skinparam DefaultFontName Courier
actor BuildingManager
participant UI #FBCBC9
participant SystemManager #d69cbc
database DB
participant SimulationEngine #a2d5c6


BuildingManager -> UI : send new task
activate UI
UI -> SystemManager : update task queue
deactivate UI
activate SystemManager
SystemManager -> DB : update task queue
SystemManager -> SimulationEngine : send task
activate SimulationEngine
SimulationEngine -> SimulationEngine : clean
SimulationEngine --> SystemManager : send post-clean data
deactivate SimulationEngine
SystemManager -> DB : update post-clean data
SystemManager --> UI : send report
deactivate SystemManager
activate UI
UI --> BuildingManager : display report
deactivate UI

@enduml
