@startuml 1
skinparam dpi 150
' skinparam DefaultFontName Courier
actor Building_Operator
participant UI #FBCBC9
participant SystemManager #d69cbc
database DB
participant SimulationEngine #a2d5c6


Building_Operator -> UI : send new task
activate UI
UI -> SystemManager : update task queue
deactivate UI
activate SystemManager
SystemManager -> DB : update task queue
SystemManager -> SimulationEngine : send task
activate SimulationEngine
SystemManager --> UI : send notification
activate UI
UI --> Building_Operator : notify operator
deactivate UI
SimulationEngine -> SimulationEngine : clean
SimulationEngine --> SystemManager : send post-clean data
deactivate SimulationEngine
SystemManager -> DB : update post-clean data
deactivate SystemManager

@enduml
