@startuml 1
skinparam dpi 150
skinparam DefaultFontName Courier
actor Building_Operator
participant UI
participant Fleet_Manager
database DB
participant Simulator


Building_Operator -> UI : send new task
activate UI
UI -> Fleet_Manager : update task queue
deactivate UI
activate Fleet_Manager
Fleet_Manager -> DB : update task queue
Fleet_Manager -> Simulator : send task
activate Simulator
Fleet_Manager --> UI : send notification
activate UI
UI --> Building_Operator : notify operator
deactivate UI
Simulator -> Simulator : clean
Simulator --> Fleet_Manager : send post-clean data
deactivate Simulator
Fleet_Manager -> DB : update post-clean data
deactivate Fleet_Manager

@enduml
