@startuml ABasicUseDiagram

actor "Building Operator" as BO
actor "Senior Manager" as SM
actor "Building Manager" as BM
actor "Field Engineer" as FE


rectangle "Cleaning Robot System" {
    usecase "Task robots" as U1
    usecase "View robot analytics" as U2
    usecase "Create robots/floors/tasks" as U3
    usecase "Create floorplan" as U4
    usecase "View/resolve errors" as U5
    usecase "Refill/empty robot capacity" as U6
}

BO --> U1
SM --> U2
BM --> U1
BM --> U3
BM --> U4 
FE --> U5 
FE --> U6

@enduml
